In [ ]:
                                        #APPLIED STATISTICS EXERCISE-1  #18/09/2024  

In [10]:
import numpy as np
a = np.array([1,2,3])
b = np.array([3,4,5])
print(type(a))
print(a.shape)
print(type(b))
print(b)
print(a[0],a[1],a[2])


<class 'numpy.ndarray'>
(3,)
<class 'numpy.ndarray'>
[3 4 5]
1 2 3


In [11]:
a[0]=5
print(a)
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
#Representation of the 2-D array
print(b[0,0],b[0,1],b[1,0])

[5 2 3]
(2, 3)
1 2 4


In [23]:
#Numpy also provides many functions to cresate an arrays:

import numpy as np
a = np.zeros((2,2)) #Create an array of all zeroes.(replacing the missing values)
print(a)

b = np.ones((2,3))  #Create an array of all ones
print(b)

c = np.full((3,5),7) #Create a constant array
print(c)

d = np.eye(2)      #Creating a 2x2 identity matrix
print(d)

e = np.random.random((2,2)) #Creating an array filled with random values (Pseudorandom number generator)
print(e)



[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]
[[1. 0.]
 [0. 1.]]
[[0.66609782 0.94228418]
 [0.0319829  0.80148319]]


In [49]:
#linspace 

# numpy.linspace(start, stop, num=50, endpoint=True , retstep=False, dtype=None, axis=0)
f = np.linspace(0, 2, 10)
print(f)

[0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111
 1.33333333 1.55555556 1.77777778 2.        ]


In [28]:
#Array sclicing 
import numpy as np
#[[1 2 3 4 ]
#[5 6 7 8 ]
#[9 10 11 12]]
a=np.array(([1,2,3,4],[5,6,7,8],[9,10,11,12]))
b=a[:2, 1:3]
print(a[0,1])
b=a[:2,1:3]
print(a[0,1])
print(a[:,:])
print(a[:2,1:3])
print(a[0:2,1:2])
print(a[2:3,0:2])
print(a[:2,1:])

2
2
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
[[2]
 [6]]
[[ 9 10]]
[[2 3 4]
 [6 7 8]]


In [29]:
a=np.array([[1,2],[3,4],[5,6]])
print(a[[0,1,2],[0,1,0]])
print(np.array([a[0,0], a[1,1], a[2,0]]))
print(a[[0,0],[1,1]])
print(np.array([a[0,1], a[0,1]]))

[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [30]:
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)
b= np.array([0,2,0,1])
print(a[np.arange(4),b])
a[np.arange(4),b]
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [33]:
#Boolean array indexing :
import numpy as np
a = np.array([[1,2],[3,4],[5,6]])
bool_idx = (a>2)
print(bool_idx)
print(a[bool_idx])
print(a[a>2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [37]:
import numpy as np
a = np.array([1,2])
print(a.dtype)
x = np.array([1.0,2.0])
print(x.dtype)
y = np.array([1,2] , dtype = np.int64)
print(y.dtype)

int32
float64
int64


In [40]:
import numpy as np
x = np.array([[1,2],[3,4],[5,6]])
y = np.array([[5,6],[7,8],[9,5]])
print(x+y)
print(np.add(x,y))
print(x-y)
print(np.subtract(x,y))
print(x/y)
print(np.divide(x,y))
print(np.sqrt(x))


[[ 6  8]
 [10 12]
 [14 11]]
[[ 6  8]
 [10 12]
 [14 11]]
[[-4 -4]
 [-4 -4]
 [-4  1]]
[[-4 -4]
 [-4 -4]
 [-4  1]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]
 [0.55555556 1.2       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]
 [0.55555556 1.2       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]
 [2.23606798 2.44948974]]


In [42]:
#Transpose 
import numpy as np
x = np.array([[1,2],[3,4]])
print(x)
print(x.T)
v = np.array([1,2,3])
print(v)
print(v.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


In [48]:
#Reshape of array :
import numpy as np
arr = np.arange(16)
print("The Original Array is:\n",arr)
arr1 = np.arange(16).reshape(2,8)
print("The Reshaped array is:\n",arr1)

The Original Array is:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
The Reshaped array is:
 [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


In [52]:
# eigen values and eigen vectors using numpy in python:

import numpy as np
x = np.array([[2, 1], [1, 1]])
eigenvalues, eigenvectors = np.linalg.eig(x)
print("The Eigenvalues is :", eigenvalues)
print("The Eigenvectors is:", eigenvectors)

The Eigenvalues is : [2.61803399 0.38196601]
The Eigenvectors is: [[ 0.85065081 -0.52573111]
 [ 0.52573111  0.85065081]]
